###########################################################################
#
# Generated by : Version 11.0 Build 208 07/03/2011 Service Pack 1 SJ Full Version
#
# Project      : DE2_SD_Card_Audio
# Revision     : DE2_SD_Card_Audio
#
# Date         : Fri Aug 12 09:27:59 +0800 2011
#
###########################################################################
 
 
# WARNING: Expected ENABLE_CLOCK_LATENCY to be set to 'ON', but it is set to 'OFF'
#          In SDC, create_generated_clock auto-generates clock latency
#
# ------------------------------------------
#
# Create generated clocks based on PLLs
derive_pll_clocks -use_tan_name
#
# ------------------------------------------


# Original Clock Setting Name: CLOCK_50
create_clock -period "20.000 ns" \
             -name {CLOCK_50} {CLOCK_50}
# ---------------------------------------------


# Original Clock Setting Name: CLOCK_27
create_clock -period "37.037 ns" \
             -name {CLOCK_27} {CLOCK_27}
# ---------------------------------------------
create_clock -period "20 ns" \
             -name {SD_CLK} [get_ports SD_CLK]

# ** Clock Latency
#    -------------

# ** Clock Uncertainty
#    -----------------

# ** Multicycles
#    -----------
# ** Cuts
#    ----

# ** Input/Output Delays
#    -------------------




# ** Tpd requirements
#    ----------------

# ** Setup/Hold Relationships
#    ------------------------

# ** Tsu/Th requirements
#    -------------------


# ** Tco/MinTco requirements
#    -----------------------



# ---------------------------------------------
# The following clock group is added to try to 
# match the behavior of:
#   CUT_OFF_PATHS_BETWEEN_CLOCK_DOMAINS = ON
# ---------------------------------------------

set_clock_groups -asynchronous \
                 -group { \
                       Audio_PLL:PLL2|altpll:altpll_component|_clk0 \
                       CLOCK_27 \
                        } \
                 -group { \
                       SDRAM_PLL:PLL1|altpll:altpll_component|_clk0 \
                       SDRAM_PLL:PLL1|altpll:altpll_component|_clk1 \
                       SDRAM_PLL:PLL1|altpll:altpll_component|_clk2 \
                       CLOCK_50 \
                        } \

# ---------------------------------------------

