// DE0_Nano_SOPC_mm_interconnect_2.v

// This file was auto-generated from altera_merlin_interconnect_wrapper_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 13.1 162 at 2014.07.02.11:18:39

`timescale 1 ps / 1 ps
module DE0_Nano_SOPC_mm_interconnect_2 (
		input  wire        altpll_sys_c2_clk,                                        //                                      altpll_sys_c2.clk
		input  wire        clock_crossing_io_0_m0_reset_reset_bridge_in_reset_reset, // clock_crossing_io_0_m0_reset_reset_bridge_in_reset.reset
		input  wire [11:0] clock_crossing_io_0_m0_address,                           //                             clock_crossing_io_0_m0.address
		output wire        clock_crossing_io_0_m0_waitrequest,                       //                                                   .waitrequest
		input  wire [0:0]  clock_crossing_io_0_m0_burstcount,                        //                                                   .burstcount
		input  wire [3:0]  clock_crossing_io_0_m0_byteenable,                        //                                                   .byteenable
		input  wire        clock_crossing_io_0_m0_read,                              //                                                   .read
		output wire [31:0] clock_crossing_io_0_m0_readdata,                          //                                                   .readdata
		output wire        clock_crossing_io_0_m0_readdatavalid,                     //                                                   .readdatavalid
		input  wire        clock_crossing_io_0_m0_write,                             //                                                   .write
		input  wire [31:0] clock_crossing_io_0_m0_writedata,                         //                                                   .writedata
		input  wire        clock_crossing_io_0_m0_debugaccess,                       //                                                   .debugaccess
		output wire [8:0]  epcs_epcs_control_port_address,                           //                             epcs_epcs_control_port.address
		output wire        epcs_epcs_control_port_write,                             //                                                   .write
		output wire        epcs_epcs_control_port_read,                              //                                                   .read
		input  wire [31:0] epcs_epcs_control_port_readdata,                          //                                                   .readdata
		output wire [31:0] epcs_epcs_control_port_writedata,                         //                                                   .writedata
		output wire        epcs_epcs_control_port_chipselect                         //                                                   .chipselect
	);

	wire         clock_crossing_io_0_m0_translator_avalon_universal_master_0_waitrequest;   // epcs_epcs_control_port_translator:uav_waitrequest -> clock_crossing_io_0_m0_translator:uav_waitrequest
	wire   [2:0] clock_crossing_io_0_m0_translator_avalon_universal_master_0_burstcount;    // clock_crossing_io_0_m0_translator:uav_burstcount -> epcs_epcs_control_port_translator:uav_burstcount
	wire  [31:0] clock_crossing_io_0_m0_translator_avalon_universal_master_0_writedata;     // clock_crossing_io_0_m0_translator:uav_writedata -> epcs_epcs_control_port_translator:uav_writedata
	wire  [11:0] clock_crossing_io_0_m0_translator_avalon_universal_master_0_address;       // clock_crossing_io_0_m0_translator:uav_address -> epcs_epcs_control_port_translator:uav_address
	wire         clock_crossing_io_0_m0_translator_avalon_universal_master_0_lock;          // clock_crossing_io_0_m0_translator:uav_lock -> epcs_epcs_control_port_translator:uav_lock
	wire         clock_crossing_io_0_m0_translator_avalon_universal_master_0_write;         // clock_crossing_io_0_m0_translator:uav_write -> epcs_epcs_control_port_translator:uav_write
	wire         clock_crossing_io_0_m0_translator_avalon_universal_master_0_read;          // clock_crossing_io_0_m0_translator:uav_read -> epcs_epcs_control_port_translator:uav_read
	wire  [31:0] clock_crossing_io_0_m0_translator_avalon_universal_master_0_readdata;      // epcs_epcs_control_port_translator:uav_readdata -> clock_crossing_io_0_m0_translator:uav_readdata
	wire         clock_crossing_io_0_m0_translator_avalon_universal_master_0_debugaccess;   // clock_crossing_io_0_m0_translator:uav_debugaccess -> epcs_epcs_control_port_translator:uav_debugaccess
	wire   [3:0] clock_crossing_io_0_m0_translator_avalon_universal_master_0_byteenable;    // clock_crossing_io_0_m0_translator:uav_byteenable -> epcs_epcs_control_port_translator:uav_byteenable
	wire         clock_crossing_io_0_m0_translator_avalon_universal_master_0_readdatavalid; // epcs_epcs_control_port_translator:uav_readdatavalid -> clock_crossing_io_0_m0_translator:uav_readdatavalid

	altera_merlin_master_translator #(
		.AV_ADDRESS_W                (12),
		.AV_DATA_W                   (32),
		.AV_BURSTCOUNT_W             (1),
		.AV_BYTEENABLE_W             (4),
		.UAV_ADDRESS_W               (12),
		.UAV_BURSTCOUNT_W            (3),
		.USE_READ                    (1),
		.USE_WRITE                   (1),
		.USE_BEGINBURSTTRANSFER      (0),
		.USE_BEGINTRANSFER           (0),
		.USE_CHIPSELECT              (0),
		.USE_BURSTCOUNT              (1),
		.USE_READDATAVALID           (1),
		.USE_WAITREQUEST             (1),
		.USE_READRESPONSE            (0),
		.USE_WRITERESPONSE           (0),
		.AV_SYMBOLS_PER_WORD         (4),
		.AV_ADDRESS_SYMBOLS          (1),
		.AV_BURSTCOUNT_SYMBOLS       (0),
		.AV_CONSTANT_BURST_BEHAVIOR  (0),
		.UAV_CONSTANT_BURST_BEHAVIOR (0),
		.AV_LINEWRAPBURSTS           (0),
		.AV_REGISTERINCOMINGSIGNALS  (0)
	) clock_crossing_io_0_m0_translator (
		.clk                      (altpll_sys_c2_clk),                                                         //                       clk.clk
		.reset                    (clock_crossing_io_0_m0_reset_reset_bridge_in_reset_reset),                  //                     reset.reset
		.uav_address              (clock_crossing_io_0_m0_translator_avalon_universal_master_0_address),       // avalon_universal_master_0.address
		.uav_burstcount           (clock_crossing_io_0_m0_translator_avalon_universal_master_0_burstcount),    //                          .burstcount
		.uav_read                 (clock_crossing_io_0_m0_translator_avalon_universal_master_0_read),          //                          .read
		.uav_write                (clock_crossing_io_0_m0_translator_avalon_universal_master_0_write),         //                          .write
		.uav_waitrequest          (clock_crossing_io_0_m0_translator_avalon_universal_master_0_waitrequest),   //                          .waitrequest
		.uav_readdatavalid        (clock_crossing_io_0_m0_translator_avalon_universal_master_0_readdatavalid), //                          .readdatavalid
		.uav_byteenable           (clock_crossing_io_0_m0_translator_avalon_universal_master_0_byteenable),    //                          .byteenable
		.uav_readdata             (clock_crossing_io_0_m0_translator_avalon_universal_master_0_readdata),      //                          .readdata
		.uav_writedata            (clock_crossing_io_0_m0_translator_avalon_universal_master_0_writedata),     //                          .writedata
		.uav_lock                 (clock_crossing_io_0_m0_translator_avalon_universal_master_0_lock),          //                          .lock
		.uav_debugaccess          (clock_crossing_io_0_m0_translator_avalon_universal_master_0_debugaccess),   //                          .debugaccess
		.av_address               (clock_crossing_io_0_m0_address),                                            //      avalon_anti_master_0.address
		.av_waitrequest           (clock_crossing_io_0_m0_waitrequest),                                        //                          .waitrequest
		.av_burstcount            (clock_crossing_io_0_m0_burstcount),                                         //                          .burstcount
		.av_byteenable            (clock_crossing_io_0_m0_byteenable),                                         //                          .byteenable
		.av_read                  (clock_crossing_io_0_m0_read),                                               //                          .read
		.av_readdata              (clock_crossing_io_0_m0_readdata),                                           //                          .readdata
		.av_readdatavalid         (clock_crossing_io_0_m0_readdatavalid),                                      //                          .readdatavalid
		.av_write                 (clock_crossing_io_0_m0_write),                                              //                          .write
		.av_writedata             (clock_crossing_io_0_m0_writedata),                                          //                          .writedata
		.av_debugaccess           (clock_crossing_io_0_m0_debugaccess),                                        //                          .debugaccess
		.av_beginbursttransfer    (1'b0),                                                                      //               (terminated)
		.av_begintransfer         (1'b0),                                                                      //               (terminated)
		.av_chipselect            (1'b0),                                                                      //               (terminated)
		.av_lock                  (1'b0),                                                                      //               (terminated)
		.uav_clken                (),                                                                          //               (terminated)
		.av_clken                 (1'b1),                                                                      //               (terminated)
		.uav_response             (2'b00),                                                                     //               (terminated)
		.av_response              (),                                                                          //               (terminated)
		.uav_writeresponserequest (),                                                                          //               (terminated)
		.uav_writeresponsevalid   (1'b0),                                                                      //               (terminated)
		.av_writeresponserequest  (1'b0),                                                                      //               (terminated)
		.av_writeresponsevalid    ()                                                                           //               (terminated)
	);

	altera_merlin_slave_translator #(
		.AV_ADDRESS_W                   (9),
		.AV_DATA_W                      (32),
		.UAV_DATA_W                     (32),
		.AV_BURSTCOUNT_W                (1),
		.AV_BYTEENABLE_W                (4),
		.UAV_BYTEENABLE_W               (4),
		.UAV_ADDRESS_W                  (12),
		.UAV_BURSTCOUNT_W               (3),
		.AV_READLATENCY                 (0),
		.USE_READDATAVALID              (0),
		.USE_WAITREQUEST                (0),
		.USE_UAV_CLKEN                  (0),
		.USE_READRESPONSE               (0),
		.USE_WRITERESPONSE              (0),
		.AV_SYMBOLS_PER_WORD            (4),
		.AV_ADDRESS_SYMBOLS             (0),
		.AV_BURSTCOUNT_SYMBOLS          (0),
		.AV_CONSTANT_BURST_BEHAVIOR     (0),
		.UAV_CONSTANT_BURST_BEHAVIOR    (0),
		.AV_REQUIRE_UNALIGNED_ADDRESSES (0),
		.CHIPSELECT_THROUGH_READLATENCY (0),
		.AV_READ_WAIT_CYCLES            (1),
		.AV_WRITE_WAIT_CYCLES           (1),
		.AV_SETUP_WAIT_CYCLES           (0),
		.AV_DATA_HOLD_CYCLES            (0)
	) epcs_epcs_control_port_translator (
		.clk                      (altpll_sys_c2_clk),                                                         //                      clk.clk
		.reset                    (clock_crossing_io_0_m0_reset_reset_bridge_in_reset_reset),                  //                    reset.reset
		.uav_address              (clock_crossing_io_0_m0_translator_avalon_universal_master_0_address),       // avalon_universal_slave_0.address
		.uav_burstcount           (clock_crossing_io_0_m0_translator_avalon_universal_master_0_burstcount),    //                         .burstcount
		.uav_read                 (clock_crossing_io_0_m0_translator_avalon_universal_master_0_read),          //                         .read
		.uav_write                (clock_crossing_io_0_m0_translator_avalon_universal_master_0_write),         //                         .write
		.uav_waitrequest          (clock_crossing_io_0_m0_translator_avalon_universal_master_0_waitrequest),   //                         .waitrequest
		.uav_readdatavalid        (clock_crossing_io_0_m0_translator_avalon_universal_master_0_readdatavalid), //                         .readdatavalid
		.uav_byteenable           (clock_crossing_io_0_m0_translator_avalon_universal_master_0_byteenable),    //                         .byteenable
		.uav_readdata             (clock_crossing_io_0_m0_translator_avalon_universal_master_0_readdata),      //                         .readdata
		.uav_writedata            (clock_crossing_io_0_m0_translator_avalon_universal_master_0_writedata),     //                         .writedata
		.uav_lock                 (clock_crossing_io_0_m0_translator_avalon_universal_master_0_lock),          //                         .lock
		.uav_debugaccess          (clock_crossing_io_0_m0_translator_avalon_universal_master_0_debugaccess),   //                         .debugaccess
		.av_address               (epcs_epcs_control_port_address),                                            //      avalon_anti_slave_0.address
		.av_write                 (epcs_epcs_control_port_write),                                              //                         .write
		.av_read                  (epcs_epcs_control_port_read),                                               //                         .read
		.av_readdata              (epcs_epcs_control_port_readdata),                                           //                         .readdata
		.av_writedata             (epcs_epcs_control_port_writedata),                                          //                         .writedata
		.av_chipselect            (epcs_epcs_control_port_chipselect),                                         //                         .chipselect
		.av_begintransfer         (),                                                                          //              (terminated)
		.av_beginbursttransfer    (),                                                                          //              (terminated)
		.av_burstcount            (),                                                                          //              (terminated)
		.av_byteenable            (),                                                                          //              (terminated)
		.av_readdatavalid         (1'b0),                                                                      //              (terminated)
		.av_waitrequest           (1'b0),                                                                      //              (terminated)
		.av_writebyteenable       (),                                                                          //              (terminated)
		.av_lock                  (),                                                                          //              (terminated)
		.av_clken                 (),                                                                          //              (terminated)
		.uav_clken                (1'b0),                                                                      //              (terminated)
		.av_debugaccess           (),                                                                          //              (terminated)
		.av_outputenable          (),                                                                          //              (terminated)
		.uav_response             (),                                                                          //              (terminated)
		.av_response              (2'b00),                                                                     //              (terminated)
		.uav_writeresponserequest (1'b0),                                                                      //              (terminated)
		.uav_writeresponsevalid   (),                                                                          //              (terminated)
		.av_writeresponserequest  (),                                                                          //              (terminated)
		.av_writeresponsevalid    (1'b0)                                                                       //              (terminated)
	);

endmodule
